apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: craftercms
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-command-executor
  namespace: craftercms
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: craftercms
subjects:
  - kind: Group
    name: eks-craftercms-support
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-pod-commands
  namespace: craftercms
subjects:
  - kind: Group
    name: eks-craftercms-support
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-command-executor
  apiGroup: rbac.authorization.k8s.io