# create cwagent service account and role binding
{{- if .Values.cwagent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cwagent.serviceAccount.name }}
  namespace: amazon-cloudwatch
{{- end -}}