# create prometheus service account and role binding
{{- if .Values.prometheus.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.serviceAccount.name }}
  namespace: amazon-cloudwatch
{{- end -}}