kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.serviceAccount.name }}
    namespace: amazon-cloudwatch
roleRef:
  kind: ClusterRole
  name: prometheus-agent-role
  apiGroup: rbac.authorization.k8s.io