apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: default-cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: "{{ .Values.awsRegion }}"
      auth:
        jwt:
          serviceAccountRef:
            namespace: external-secrets
            name: external-secrets