apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-encryption-key-salt
spec:
  secretStoreRef:
    name: default-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: config-encryption-key-salt
    creationPolicy: Owner
  refreshInterval: "1m"
  dataFrom:
    - extract:
        key: "{{cluster_name}}/config-encryption-key-salt"