apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-https-server-credentials
spec:
  secretStoreRef:
    name: default-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: git-https-server-credentials
    creationPolicy: Owner
  refreshInterval: "1m"
  dataFrom:
    - extract:
        key: "{{cluster_name}}/git-https-server-credentials"