description: EBS CSI Driver and Storage Classes
name: storage-addons
version: 1.12
dependencies:
  - name: aws-ebs-csi-driver
    version: 2.38.1
    repository: https://kubernetes-sigs.github.io/aws-ebs-csi-driver