description: External Secrets Operator and Secret Stores
name: external-secrets
version: 1.10
dependencies:
  - name: external-secrets
    version: 0.12.1
    repository: https://charts.external-secrets.io